* notmuch

Notmuch is just an indexer it doesn't pull emails from the server (hence the
name), so you need a provider: [[https://isync.sourceforge.io/][mbsync]] and [[https://www.offlineimap.org/][offlineimap]] are universal ones.

I use Gmail, so I provide instructions on how to configure Notmuch with [[https://github.com/gauteh/lieer][lieer]] —
a synchronizer specifically designed for Gmail.

** Install Notmuch and dependencies

- On Fedora:
  #+begin_src sh
  sudo dnf install notmuch notmuch-devel emacs-notmuch
  sudo dnf install python3-google-api-client python3-google-auth-oauthlib python3-notmuch2
  #+end_src

** Setup Notmuch

Create the notmuch config file at =~/.config/notmuch/default/config=. Here,
=default= is the profile name. This configuration sets your root mail folder to
=~/.mail=.

#+begin_src conf
[database]
path=.mail

[user]
name=John Smith
primary_email=john_smith@gmail.com
other_email=john_smith@outlook

[new]
tags=new
ignore=/.*[.](json|lock|bak)$/
#+end_src

Run ~notmuch~ to create database.

** Setup Lieer

Clone the Lieer [[https://github.com/gauteh/lieer][repository]], and execute ~pip install .~ in it.

Make a directory for the lieer storage and state files (local repository). This
assumes your root mail folder is in =~/.mail= and that this folder is already
exist and set up with ~notmuch~.

#+begin_src sh
$ mkdir ~/.mail/account.gmail
#+end_src

The executable is called ~gmi~ and it should always be run from the local mail
repository unless otherwise specified.

#+begin_src sh
$ cd ~/.mail/account.gmail
$ gmi init john_smith@gmail.com
#+end_src

~gmi init~ will open your browser and request limited access to your e-mail.
The access token is stored in =.credentials.gmailieer.json=

** Notmuch hooks
*** pre-new

=pre-new= hook is invoked by the ~notmuch new~ command before scanning or importing
new messages into the database. If this hook exits with a non-zero status,
notmuch will abort further processing.

- =~/.config/notmuch/default/hooks/pre-new=

#+begin_src bash
#!/bin/bash

cd ~/.mail/account.gmail/ && gmi sync
#+end_src

*** post-new

=post-new= hook is invoked by the ~notmuch new~ command after new messages have been
imported into the database and initial tags have been applied.

- =~/.config/notmuch/default/hooks/post-new=

#+begin_src bash
#!/bin/bash

# Immediately archive all "sent" messages
notmuch tag -new -- tag:sent

# Retag all "new" messages "inbox" and "unread"
notmuch tag +inbox +unread -new -- tag:new
#+end_src

** Initiall tagging

The described configuration uses the =new= tag approach for new messages from the
[[https://notmuchmail.org/initial_tagging/][manual]]. The following setting
#+begin_src sh
[new]
tags=new
#+end_src
in notmuch config file make all new messages to get the =new= tag, which
than in =post-new= hook is replaces with =inbox= and =unread= tags.

** Open =text/html= mime part in external browser

Use =v= or =.v= in a Notmuch show buffer. If you get a file not found error,
then on Linux you need to create =~/.mailcap= and copy into it the line from
=/etc/mailcap= that starts with =text/html;=, with =copiousoutput= stripped.

Typically, it would be something like this:
#+begin_src conf
text/html; /usr/bin/xdg-open %s
#+end_src

Stripping =copiousoutput= prevents temporary files from being deleted from =/tmp=.
This is usually not a problem, since modern Linux distributions manage =/tmp=
automatically. For example, Fedora removes files not accessed for 10 days via
=systemd-tmpfiles-clean.service=.
