#+title: Offline outliner and PKM powered by Org-mode and Hel

One of the best outliners and personal knowledge management systems on the market.
- *Offline-first* — all your data belongs only to you.
- *Unmatched editing* capabilities of any outliner available today.
- *Org-mode advantages:*
  - Rich markup — more powerful and stable than Markdown.
  - Task management.
  - The best code snippet support of any outliner.
  - Tables.
  - LaTeX as a first-class citizen (like HTML for Markdown).
- *Bidirectional links* for seamless navigation.
- *Daily notes* — you main scratchpad and better "Inbox".

* helheim-org
** Customization

- ~helheim-org-heading-padding~ ::
  Add extra padding to Org mode headings to make them more spacious. This is
  done by increasing the height of the space character between the stars that
  denotes the heading level and the heading text. See help for
  ~set-face-attribute~ -> ~:height~ for the meaning of the value.

  Must be set with ~setopt~ function!

* helheim-org-node

Install and configure [[https://github.com/meedstrom/org-node][Org-node]].

** Customization

- ~helheimg-org-node-visit-backlink-in-another-window~ ::
  When set =Enter= in backlinks buffer opens target in another window.
  (defaults: ~nil~)

* helheim-daily-notes

Daily notes is your main scratchpad. Every day you get a clean slate.
It’s a modern alternative and an evolution of the traditional "Inbox" note.

#+begin_quote
A rule of thumb — if you don’t know where to put a note, don’t think about
files or folders; just put it into your daily note. If you aren’t using this
method yet, you’ll find how revealing it is.
#+end_quote

- =SPC n d= ::
  Open today’s note. With =M-u=, interactively choose a date and open the daily
  note for that date.

- =[[= / =]]= :: Open the *previous* / *next* daily note.
